name: Crawler

on:
  push:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  crawl:
    name: 3GPP documents fetching
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install mdbtools
        run: sudo apt-get install mdbtools
      - name: Install gem
        run: |
          gem install relaton-cli
      - name: Fetch documents
        run: |
          # rm -f data/*
          relaton fetch-data status-smg-3GPP
      - name: Push data
        run: |
          echo `date` > flag.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add data/* flag.txt current.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m 'update documents' && git push)
